### ISSUE TITLE
No hay datos de comarcas en /theme-aragon/data/comarca/2014Q1/  y alguna cosilla más

### ISSUE THREAD

**Issue by srlopez** [aragonopendata/presupuesto#5]
Hola David
Tal y como indicas en INSTALL.MD ejecutando 
**$ python manage.py load_budget_data comarca 2014Q1**
Obtengo el siguiente error
**IOError: [Errno 2] No such file or directory: '/home/santi/Dev/py/presupuesto/project/../theme-aragon/data/comarca/2014Q1/clasificacion_economica.csv'**
Creo que no has subudo algunos datos de comarcas

Al correr el server
**$ python manage.py runserver**
Todo correcto hasta que accedo al navegador localhost:8000 y aparece en la página:
**A server error occurred.  Please contact the administrator.**

En la consola de ejecución continua el siguiente mensaje
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 92, in get_response
    response = middleware_method(request)
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/locale.py", line 21, in process_request check_path = self.is_language_prefix_patterns_used()
  File "/usr/local/lib/python2.7/dist-packages/django/middleware/locale.py", line 56, in is_language_prefix_patterns_used for url_pattern in get_resolver(None).url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 347, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py", line 342, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
 **File "/home/santi/Dev/py/presupuesto/project/urls.py", line 5, in <module>
    from django.views.generic.simple import direct_to_template
ImportError: No module named simple**
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/handlers.py", line 72, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 255, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 178, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 217, in handle_uncaught_exception return debug.technical_500_response(request, *exc_info)
  File "/usr/local/lib/python2.7/dist-packages/django/views/debug.py", line 69, in technical_500_response html = reporter.get_traceback_html()
  File "/usr/local/lib/python2.7/dist-packages/django/views/debug.py", line 298, in get_traceback_html
    return t.render(c)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 188, in render
    nodelist.append(node.render(context))
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 84, in render
    output = self.filter_expression.resolve(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 578, in resolve
    obj = self.var.resolve(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 728, in resolve
    value = self._resolve_lookup(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 779, in _resolve_lookup
    current = current()
  **File "/home/santi/Dev/py/presupuesto/project/settings.py", line 203, in COMPRESS_JINJA2_GET_ENVIRONMENT from coffin.common import env
ImportError: cannot import name env**
[06/May/2015 19:50:15] "GET / HTTP/1.1" 500 59

Settings
201. # Needed by django_compressor. See http://django-compressor.readthedocs.org/en/latest/jinja2/#id1
202. def COMPRESS_JINJA2_GET_ENVIRONMENT():
203.     from coffin.common import env
204.     return env

El modulo django-compressor y coffin están instalados 
Coffin==2.0.1
Django==1.5
Jinja2==2.7.3
Pygments==2.0.2
django-appconf==1.0.1
django-compressor==1.5
django-jasmine==0.4.1

En urls.py
5. from django.views.generic.simple import direct_to_template

No entiendo porque da error. Está Django 1.5 instalado

Gracias de antemano

**Comment by dcabo** [comment]
Hola, perdona el retraso.

Los datos de comarcas y municipios ocupan mucho, y además daría trabajo tenerlos actualizados en el repo, por eso los dejamos fuera. Tendrías que bajarlos de Aragón Open Data ([comarcas](http://opendata.aragon.es/catalogo/presupuesto-y-ejecucion-presupuestaria-de-comarcas-de-aragon), [municipios](http://opendata.aragon.es/catalogo/presupuesto-y-ejecucion-presupuestaria-de-municipios-de-aragon)), pero en realidad ese paso es opcional, puedes trabajar perfectamente sólo con los presupuestos del Gobierno. Voy a aclarar esto en la documentación.

Sobre el otro error, es la primera vez que veo algo similar. ¿Puedes probar con Django 1.4 y ver si se repite? Gracias.

**Comment by srlopez** [comment]
Gracias David,

Django 1.4.2  instalado y el error 'simple' corregido.

No vale 1.4 a secas,  ya que no tiene django.utils.six

pip install -v django=="1.4.2"
pip install -v coffin=="0.4.0"  #Coffin debe ser ese, el último tampoco
vale.


Una última cuestión,
Las gráficas que presentas en la web de presupuestos, son distintas que las
que veo en mi equipo.
¿Quizás sea que no tengo todos los datos? y al no poder comparar con otros
años no puede presentar una gráfica de evolución y presenta un cuadro de
superficies proporcionales
.
[image: Imágenes integradas 2]

Dime si te puedo ayudar en algo.
Gracias

Y añádeme si puedes a tus contactos
https://www.linkedin.com/in/srlopezh






 *Atentamente.*



  *  Santiago R.*
   srlopezh@gmail·com
   675 703 184

**Comment by srlopez** [comment]
Gracias David
La solución era, como me has indicado instalar django 1.4.2 a la que añadimos coffin 0.4.0

**Comment by dcabo** [comment]
Hola,

Gracias por probar con Django 1.4, que es lo que está desplegado en producción. Sabía que la aplicación no funcionaba con 1.6, pero estaba convencido de que sí funcionaría con 1.5. Intentaré reproducir el problema, pero mientras tanto voy a actualizar la documentación para aclarar esto.

Sobre lo de que los gráficos son distintos, en efecto, si sólo hay un año de presupuestos aparece un treemap en vez del gráfico de capas. Puedes descargar más años (en CSV) de [Aragón Open Data](http://opendata.aragon.es/catalogo/catalogo.html?q=presupuestos), pero añadiré también enlaces a la documentación para que sea más sencillo.

/david

**Comment by dcabo** [comment]
Por cierto, tengo pendiente añadir issues al repo con las posibles mejoras, durante el desarrollo inicial gestionaba los issues en otro repo (privado). Si hay alguna mejora o error que tengas en la cabeza me dices y lo hablamos.
